# Intranet/OsBundle/Resources/config/admin.yml
services:
    sonata.admin.defeito:
        class: Intranet\OsBundle\Admin\DefeitoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Configuração", label: "Defeito" }
        arguments:
            - ~
            - Intranet\OsBundle\Entity\Defeito
            - ~
        calls:
            - [ setTranslationDomain, [IntranetOsBundle]]