parameters:
#    intranet_conta.example.class: Intranet\Bundle\ContaBundle\Example

services:
#    intranet_conta.example:
#        class: %intranet_conta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
