<?php

namespace Intranet\OsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DefeitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefeitoRepository extends EntityRepository
{
}
